# -*- coding: utf-8 -*-
"""平台元数据配置 - 6 大档案源的展示信息

从 app.py 抽出（优化优先级 2-F）。新增平台时只改本文件 + 入库脚本即可。
"""
from __future__ import annotations

PLATFORM_META = {
    "frus": {
        "name": "FRUS",
        "long_name": "Foreign Relations of the United States",
        "cn_name": "《美国对外关系文件集》",
        "subtitle": "美国对外关系文件集 1941-1950 中国卷",
        "intro": "美国国务院公开编辑、按外交决策线索精选的官方文献年鉴。1861 年至今由 Office of the Historian 主持，是研究美国外交史最权威的一手史料丛书。本平台聚焦其 1941-1950 年中国卷册中与民盟相关的部分。",
        "perspective": "美方驻华外交官视角 —— 大使馆/领事馆给国务院的报告 + 马歇尔来华使团与民盟领袖的会谈记录",
        "coverage": "1941.3 民盟成立 — 1947.10 民盟被取缔 — 1949.10 新中国成立 — 1950 内战收尾",
        "highlights": [
            '<a href="/search?q=Marshall+%E4%BC%9A%E8%B0%88+%E5%BC%A0%E6%BE%9C+%E7%BD%97%E9%9A%86%E5%9F%BA&platform=frus">马歇尔与张澜、罗隆基、张君劢、周恩来等的逐字会谈记录</a>',
            '<a href="/search?q=Stuart+Democratic+League+1947&platform=frus">司徒雷登大使关于民盟政治处境的连续报告（特别是 1947 取缔前后）</a>',
            '<a href="/search?q=Lo+Lung-chi+October+28+1947+memorandum&platform=frus">罗隆基 1947.10.28 在使馆软禁期间的亲历对话备忘录（page 316）</a>',
            '<a href="/search?q=Carsun+Chang+Marshall+November+1+1947&platform=frus">张君劢 1947.11.1 致马歇尔函（page 333）—— 民盟取缔后第 5 天的民盟人士陈情</a>',
            '<a href="/search?q=Democratic+League+PCC+representatives+statement&platform=frus">12 位民盟政协代表 1946 联名声明（page 228）</a>',
        ],
        "status": None,
        "status_class": "ok",
        "active": True,
    },
    "wilson": {
        "name": "Wilson Center",
        "long_name": "Wilson Center Digital Archive",
        "cn_name": "威尔逊中心数字档案",
        "subtitle": "数字伍德罗·威尔逊中心档案",
        "intro": "美国伍德罗·威尔逊国际学者中心（Woodrow Wilson International Center for Scholars）建立的数字档案，聚焦冷战及国际关系一手史料。最大特点是收录大量来自苏联档案、东欧档案、中国共产党档案的解密文件。",
        "perspective": "苏联档案 + 中共内部档案 + 东欧档案视角 —— FRUS 美方视角不可替代的「另一面」",
        "coverage": "1945-1950 中共与苏联高层互动 / 1949 米高扬西柏坡密访 / 1949.7 刘少奇访苏 / 苏联驻华大使彼得罗夫、罗申会谈记录",
        "highlights": [
            '<a href="/search?q=Mikoyan&platform=wilson">米高扬访华回忆录（1949.1.31 - 2.7 西柏坡密访）⭐⭐⭐</a>',
            '<a href="/search?q=Liu+Shaoqi+Stalin&platform=wilson">刘少奇 ↔ 斯大林会谈备忘录（1949 年 7 月访苏，中苏分工框架）⭐⭐⭐</a>',
            '<a href="/search?q=Democratic+parties+CPPCC&platform=wilson">民主党派与政协预备委员会（苏联档案分类下的民盟代表人物名单）</a>',
            '<a href="/search?q=Petrov&platform=wilson">彼得罗夫大使 ↔ 周恩来 / 毛泽东 / 王若飞 多次会谈</a>',
            '<a href="/search?q=Mao+Stalin+Kovalev&platform=wilson">毛泽东、刘少奇、科瓦廖夫、斯大林之间 1949 年建政前后密电</a>',
            '<a href="/search?q=Roshchin&platform=wilson">罗申大使 ↔ 周恩来 1949.11.10 会谈记录</a>',
        ],
        "status": None,
        "status_class": "ok",
        "active": True,
        "todo_note": "",
    },
    "cia": {
        "name": "CIA FOIA",
        "long_name": "CIA FOIA Reading Room",
        "cn_name": "美国中央情报局已解密文件阅览室",
        "subtitle": "美国中央情报局已解密文件（archive.org 镜像）",
        "intro": "美国中央情报局根据《信息自由法》（FOIA）公开的已解密文件全文检索系统，本平台通过 archive.org 的 ciareadingroom collection 镜像获取一手 PDF 与 OCR 文本。",
        "perspective": "美方情报系统视角 —— 与 FRUS 外交部门视角形成互补",
        "coverage": "1946-1954 民盟相关档案 21 篇（核心专题）",
        "highlights": [
            '<a href="/doc/cia-meng:CIA-RDP82-00457R002800130003-8">1949-05-23 CHINA DEMOCRATIC LEAGUE MEMBERS\' ESCAPE FROM SHANGHAI（民盟成员上海撤离香港）</a>',
            '<a href="/doc/cia-meng:cia-readingroom-document-cia-rdp82-00457r004000340003-1">1949-12-20 LO LUNG-CHI（罗隆基专档）</a>',
            '<a href="/doc/cia-meng:CIA-RDP82-00457R004600450010-5">1950-04-04 CHANG LAN（张澜专档）</a>',
            '<a href="/doc/cia-meng:CIA-RDP82-00457R005200480001-5">1950-07-12 LEADING MEMBERS OF THE CHINA DEMOCRATIC LEAGUE（民盟领导成员名单）</a>',
            '<a href="/doc/cia-meng:cia-readingroom-document-cia-rdp82-00457r006100780010-2">1950-11-09 ROLE OF NON-COMMUNIST POLITICAL PARTIES IN PEIPING（第三方面政党在北平的作用）</a>',
            '<a href="/doc/cia-meng:cia-readingroom-document-cia-rdp61s00527a000200010065-4">1954-09-16 ROSTER OF PRESIDIUM OF FIRST CONGRESS（一届人大主席团名单）</a>',
        ],
        "status": None,
        "status_class": "ok",
        "active": True,
        "todo_note": "",
    },
    "hoover": {
        "name": "Hoover Institution",
        "long_name": "Hoover Institution Library & Archives",
        "cn_name": "斯坦福大学胡佛档案馆",
        "subtitle": "胡佛档案馆 · 现场调档实物拍照",
        "intro": "斯坦福大学胡佛研究所档案馆收藏 20 世纪重要政治、外交人物的私人卷宗。本卡片下的资料系研究者亲赴斯坦福现场调阅原件、实物拍照后整理成 PDF 入库，并非公网下载。",
        "perspective": "人物个人卷宗视角 —— 私人通信、未刊文稿、信件原件等无法从公网获得的一手实物",
        "coverage": "张君劢档案（Carsun Chang Papers, 1946-1962, 2 oversize boxes）—— 联合政府前景、军事改编协议、与第三方面联络通信等",
        "highlights": [
            '<a href="/search?q=Carsun+Chang+Papers&platform=hoover">Carsun Chang Papers（张君劢档案）· 1946-1962 · 2 oversize boxes · 现场调档实物</a>',
            '<a href="/search?q=Carsun+Chang+Marshall&platform=hoover">民盟筹建期、政协会议期间张君劢与第三方面人物私人通信</a>',
            '<a href="/search?q=Carsun+Chang+coalition&platform=hoover">1946-1947 联合政府讨论手稿与未刊文献</a>',
        ],
        "status": None,
        "status_class": "ok",
        "active": True,
        "todo_note": "区别于公网批量抓取——所有资料系研究者赴斯坦福现场调阅、拍照、整理为 PDF 后入库。下一步：扫描件 OCR + 翻译 + 入库。",
    },
    "drnh": {
        "name": "台北档案史料",
        "long_name": "台北档案史料文物查询系统",
        "cn_name": "台湾地区档案数字典藏",
        "subtitle": "民国政府最高层视角 · 蒋中正档案 · 戴笠/保密局呈件",
        "intro": "本平台台北方面所藏中国大陆时期民国政府、总统府、行政院及党国要员档案文物。「档案史料文物查询系统」（ahonline.drnh.gov.tw）目录与元数据全开放，本平台按 1941—1950 年时间线整理民盟相关核心档案。",
        "perspective": "国民政府决策视角 + 军事情报视角 —— 与 FRUS（美方外交）、CIA（美方情报）、Wilson Center（苏方）、HathiTrust 港媒（公开舆论）构成多方视角下的民盟完整图景",
        # 注：coverage 数字（如「核心 X 篇」「共 Y 篇」）在 source_page() 里动态填入，
        # 这里用 {n_a}、{n_total} 占位，避免硬编码导致数据更新后过时
        "coverage": "1941-1950 民盟相关核心档案 {n_a} 篇（已严格逐条审视，剔除同名异人与擦边命中）。蒋中正档案 + 国民政府档案为主体，含戴笠/保密局呈件、蒋介石作战会报对民盟指示、三省参议会反驳张澜系列等。",
        "highlights": [
            '<a href="/search?q=%E6%B0%91%E4%B8%BB%E5%90%8C%E7%9B%9F+%E5%B7%A6%E8%88%9C%E7%94%9F+%E5%BC%A0%E5%90%9B%E5%8A%A2&platform=drnh">1945 戴笠呈蒋中正民盟分子左舜生张君劢拟从事调解国共纠纷（最高密件）⭐⭐⭐⭐⭐</a>',
            '<a href="/search?q=%E8%B5%AB%E5%B0%94%E5%88%A9+%E5%BC%A0%E7%94%B3%E5%BA%9C+%E8%91%A3%E6%97%B6%E8%BF%9B&platform=drnh">1945 戴笠呈蒋中正赫尔利曾召民主同盟张申府董时进谈话要点</a>',
            '<a href="/search?q=%E4%BF%9D%E5%AF%86%E5%B1%80+%E9%AD%8F%E5%BE%B7%E8%BF%88&platform=drnh">1947 保密局呈蒋中正民盟向魏德迈使团活动情形续报 ⭐⭐⭐⭐⭐</a>',
            '<a href="/search?q=%E4%BD%9C%E6%88%98%E4%BC%9A%E6%8A%A5+%E5%AF%B9%E6%B0%91%E4%B8%BB%E5%90%8C%E7%9B%9F&platform=drnh">1947 蒋中正主持作战会报对民主同盟事有所指示（最高决策档）⭐⭐⭐⭐⭐</a>',
            '<a href="/search?q=%E9%9D%92%E6%B5%B7%E7%9C%81+%E5%BC%A0%E6%BE%9C+%E8%8D%92%E8%B0%AC&platform=drnh">1946.7 山东 → 四川 → 青海三省参议会联动反驳民盟主席张澜荒谬言论系列（3 件）</a>',
            '<a href="/search?q=%E9%A1%BE%E7%A5%9D%E5%90%8C+%E6%B0%91%E4%B8%BB%E5%90%8C%E7%9B%9F%E7%AC%AC%E4%B8%80%E5%86%9B&platform=drnh">1946 顾祝同电蒋中正共军以民主同盟第一军名义改编（军事档）</a>',
            '<a href="/search?q=%E6%B5%99%E5%A4%A7+%E6%B0%91%E7%9B%9F+%E6%88%92%E4%B8%A5&platform=drnh">1947 沈鸿烈电蒋中正浙大学生罢课共党民盟分子戒严</a>',
        ],
        "status": None,
        "status_class": "ok",
        "active": True,
        "todo_note": "元数据 100% 访客可达；档案原图原档系统要求注册会员（访客版含水印）。本平台已入库 {n_total} 条元数据（默认显示 A 档 {n_a} 条核心，按时间线排序），原文图像请点击「原档系统」按钮在原系统查看。",
    },
    "hathitrust": {
        "name": "HathiTrust / IA",
        "long_name": "HathiTrust / Internet Archive",
        "cn_name": "数字图书馆联盟",
        "subtitle": "公开出版一手资料 / 当时报刊",
        "intro": "HathiTrust 由美国大学图书馆联盟建立的数字图书馆；Internet Archive 是开放的全球数字资源平台。本平台已接入 1946-1949 香港英文报纸（China Mail / Hong Kong Telegraph）对民盟事件的当时报道，构成完整的港媒时间序列。",
        "perspective": "1940s 香港英文报刊视角 —— 民盟从政协参与、国大缺席、被宣布「非法」到响应五一口号、张澜软禁的当时舆论现场记录",
        "coverage": "1946-1949 香港 China Mail / Hong Kong Telegraph 共 42 期，覆盖民盟史关键节点：1946 政协会议 → 1946 国民大会 → 1947 联合政府讨论 → 1947 民盟「非法」 → 1948 民盟香港一届三中全会 → 1948 响应五一口号 → 1949 张澜上海软禁 → 1949 解放战争南下",
        "highlights": [
            '<a href="/search?q=China+Mail+PCC&platform=hathitrust">1946-01-11 / 01-28 / 01-29 / 02-01 / 02-26 China Mail：政协会议召开期间到决议落幕（共 5 期连续追踪）</a>',
            '<a href="/search?q=China+Mail+Chang+Lan&platform=hathitrust">1946-08-23 / 10-22 / 10-30 / 11-26 / 11-27 港媒:张澜动向 + 第三方面对国民大会的拒绝立场</a>',
            '<a href="/search?q=China+Mail+1947+coalition&platform=hathitrust">1947-03-10 / 03-24 / 04-14 / 04-26 / 05-26 / 06-05 / 06-19 / 06-27 / 07-31 China Mail：1947 上半年联合政府讨论、政府改组、学生运动到内战全面化（9 期高密度报道）</a>',
            '<a href="/search?q=China+Mail+Civil+War&platform=hathitrust">1947-08-04 / 08-29 港媒：内战阶段民盟动向</a>',
            '<a href="/search?q=China+Mail+outlaw+Democratic+League&platform=hathitrust">1947-10-06 / 10-24 / 10-29 / 10-30 / 11-05 China Mail：民盟被宣布「非法」+ 总部解散全过程港媒 5 期系列报道</a>',
            '<a href="/search?q=China+Mail+Hong+Kong+Plenary&platform=hathitrust">1947-12-23 / 12-31 / 1948-01-06 / 02-03 / 03-02 / 03-09 China Mail：民盟解散后到香港一届三中全会前后港媒持续追踪（6 期）</a>',
            '<a href="/search?q=China+Mail+May+Day&platform=hathitrust">1948-04-23 / 05-19 / 08-30 / 09-04 / 12-02 China Mail：响应中共「五一口号」+ 解放战争战略反攻期（5 期）</a>',
            '<a href="/search?q=China+Mail+Shanghai+Chang+Lan&platform=hathitrust">1949-01-07 / 01-12 / 01-17 / 06-03 / 06-20 港媒：张澜上海软禁期 + 联合政府筹建讨论（5 期）</a>',
        ],
        "status": None,
        "status_class": "ok",
        "active": True,
        "todo_note": "",
    },
}
